### ISSUE TITLE
Error disabling or enabling job

### ISSUE THREAD

**Issue by chris-orchard** [jenkinsci/google-chat-notification-plugin#10]
I raised https://issues.jenkins-ci.org/browse/JENKINS-53883 getting an error when trying to enable or disable jobs. This has been triaged as a bug with the plugin and the comment:

> https://github.com/jenkinsci/google-chat-notification-plugin/blob/master/src/main/java/io/cnaik/GoogleChatNotification.java#L40...L42
> All three lines are bugs.

**Comment by chris-orchard** [comment]
Is there any update on this? I'm still getting the same issue with 1.4.

**Comment by chiragnaik** [comment]
I am working on the fix

**Comment by Ryudo302** [comment]
Hi @chris-orchard!

Are you still getting the error? I couldn't reproduce it now with 1.5.
