### ISSUE TITLE
Emoji support in messages?

### ISSUE THREAD

**Issue by abhishekdev** [jenkinsci/google-chat-notification-plugin#11]
Emojis in message content do not show up in Google Chat. They show up as `??` based on the number of bytes in the multibyte emoji character.

Here is a sample fragment from Jenkinsfile:
```groovy
post {
    always {
      script {
        def content = [
          buildStatusIcon: currentBuild.currentResult == 'SUCCESS' ? '✅️' : '❌️',
          buildStatus: currentBuild.currentResult,
          displayName: currentBuild.fullDisplayName,
          commitRef: env.GIT_COMMIT == null ? '' : env.GIT_COMMIT.take(7)
        ]

        googlechatnotification(
          url: 'id:gchat-sampleroomid',
          message: "${content.buildStatusIcon} *${content.buildStatus}* building rev `${content.commitRef}`\n- <${env.RUN_DISPLAY_URL}|${content.displayName}>",
          sameThreadNotification: true
        )
      }
    }
  }
```

### CURRENT:

?? **SUCCESS** building rev `1a0405d`
\- [#12345](http://example.com)

### EXPECTED:

✅️ **SUCCESS** building rev `1a0405d`
\- [#12345](http://example.com)

Not sure if I am missing something related to how things get encoded in groovy or in the plugin code.

**Comment by chiragnaik** [comment]
Let me check how to make this thing work

**Comment by Max-Sundar-vine** [comment]
Any updates on this emoji support?

**Comment by shqear93** [comment]
any updates?

**Comment by Redirts** [comment]
Well actually that doesn't help when the field is dynamic and contains a person's name with accents....unless you could wrap that field in some unicode converter function...

**Comment by 0sanity** [comment]
Heads up, a recent change broke this solution
https://github.com/jenkinsci/google-chat-notification-plugin/pull/48

Change the `\\u` to just `\u` and it works again

**Comment by Ryudo302** [comment]
> Heads up, a recent change broke this solution #48
> 
> Change the `\\u` to just `\u` and it works again

Hello @0sanity!

I think that this problem was introduced in v.1.7 and fixed in v.1.7.1. Have you already updated to 1.7.1?

Please let me know if you're still having problems with emojis.

**Comment by Ryudo302** [comment]
Testing with this configuration for _message_:
![image](https://github.com/jenkinsci/google-chat-notification-plugin/assets/8527036/ca4b3955-a3b8-43e9-bc24-32f3ddef2ec1)

I could see that the emojis are correctly printed in Google Chat:
![image](https://github.com/jenkinsci/google-chat-notification-plugin/assets/8527036/8e24ec97-e967-46ca-bd48-e3a42eda45f1)

So, I think that this issue is now solved.
