### ISSUE TITLE
Message description is not clear

### ISSUE THREAD

**Issue by SaimonL** [jenkinsci/google-chat-notification-plugin#17]
The document is not clear about how to use the message. All it says is:

**message

This is a mandatory String parameter.
Notification message to be sent.
Supports all token macro variables for pipeline as well as build jobs.**

I have put "BIS" (project name) in the message and all I see in the Google Hangout is "BIS" after the test has passed and thats it. No success or failure or anything else.

![jenkins](https://user-images.githubusercontent.com/7557791/59353661-78034d00-8cf1-11e9-8887-a91588d7ca1f.png)

**Comment by slux83** [comment]
Hi I have the same issue. What should I write in the message in order to get the result of the job?

**Comment by slux83** [comment]
You can do it this way, via the token plugin.
Your message will be something like this `${PROJECT_NAME} : Build #${BUILD_NUMBER} - ${BUILD_STATUS}: Check output at ${BUILD_URL}`

**Comment by Jorgeadrianmelgar** [comment]
The document is not clear about how to use the message. All it says is:

**message

This is a mandatory String parameter.
Notification message to be sent.
Supports all token macro variables for pipeline as well as build jobs.**

I have put "BIS" (project name) in the message and all I see in the Google Hangout is "BIS" after the test has passed and thats it. No success or failure or anything else.

#53

**Comment by Ryudo302** [comment]
@SaimonL, @slux83, @Lalit-1219, @Jorgeadrianmelgar,
Hi!
The README has been updated with more information and examples. Please feel free to give any feedback about it.
