### ISSUE TITLE
Cards Support

### ISSUE THREAD

**Issue by asgoel** [jenkinsci/google-chat-notification-plugin#18]
It seems like there is support for cards, but it is flagged off (https://github.com/jenkinsci/google-chat-notification-plugin/blob/ffacf6a78dc8b37d5e85dde90d8f17fa092be3a6/src/main/java/io/cnaik/service/CommonUtil.java#L66). Are there blockers to enable this?

**Comment by soulkyiro** [comment]
Is there a forecast of when the service will support Card message, or is there a way to take advantage of a feature and send it?
