### ISSUE TITLE
Google Chat Dark Mode Support

### ISSUE THREAD

**Issue by mattphi** [jenkinsci/google-chat-notification-plugin#26]
Now that google has added a dark theme to the chat window, you can see the hard coded colours in the jenkins bot.

![image](https://user-images.githubusercontent.com/15526542/131267827-83eb07ee-9071-431b-bf91-cff8a756b3bc.png)

My suggestions is that the colours change based on the [data-theme="dark"] that has been applied to the parent element on the page

Thanks,
Matt

**Comment by Ryudo302** [comment]
Hi, @mattphi!

Sorry, but I think that you're talking about the [Jenkins Bot App](https://support.google.com/chat/answer/9632691?hl=en&co=GENIE.Platform%3DAndroid), not this plugin.
