### ISSUE TITLE
Build failure Logs 

### ISSUE THREAD

**Issue by pankaj301994** [jenkinsci/google-chat-notification-plugin#29]
### What feature do you want to see added?

I have integrated this plugin with Jenkins in my project and it is working fine showing proper build status. Now I want to send build failure log to chat group but unable to do so. Can you please add this feature if it is already added then please help me with syntax. Thanks

**Comment by pankaj301994** [comment]
Current syntax is 
```
 post{
        always{
            emailext attachLog: true,
            body: "<body><p><font size='+2'><b>Build status: </b>${currentBuild.currentResult} <br><b>Jenkins Job: </b>${env.JOB_NAME}<br><b>Build Number: </b>${env.BUILD_NUMBER}</font><br>View More info at:  <b> ${env.BUILD_URL}</b></font></p></body>",subject: "Avatus Development : Jenkins Build Job : ${env.JOB_NAME}", to: 'rajiv.pandey@appinventiv.com,bilal.zaidi@appinventiv.com'
          googlechatnotification message: '${PROJECT_NAME} : Build #${BUILD_NUMBER} - ${BUILD_STATUS} : Check output at ${BUILD_URL}console', notifyAborted: true, notifyBackToNormal: true, notifyFailure: true, notifyNotBuilt: true, notifySuccess: true, notifyUnstable: true, suppressInfoLoggers: true, url: 'id:credential_id_for_avatus_chat_room'
        }
```
I am receiving a logs on mail but not chat group

**Comment by dannyroy22** [comment]
Did you find solution on this??

Ifyes then please let us know

**Comment by Ryudo302** [comment]
Currently is not possible to send attachments with the messages, only links ([see here)](https://stackoverflow.com/questions/67735842/how-to-send-an-attachment-in-google-chat-via-bot-webhook).

To send a link to the log, you could do something like this in the message text:
`(<${env.BUILD_URL}|Build info>)`
