### ISSUE TITLE
Is there a way to suppress the Chat Notification Response

### ISSUE THREAD

**Issue by ryangrey** [jenkinsci/google-chat-notification-plugin#3]
when using the plugin in "Post-build Actions" there doesn't seem to be a way to suppress the json response ?

**Comment by chiragnaik** [comment]
Hello Ryan, 
Currently there is no support for suppressing JSON response. But in next release which is on coming Monday, there will be support for suppressing the same.

**Comment by chiragnaik** [comment]
New version of plugin is available. You can suppress logs by passing suppressInfoLogs: true or by checking suppressInfoLogs check box in Post Build Actions
