### ISSUE TITLE
GoogleChatNotification setNotifySuccess() expects boolean but received String Error

### ISSUE THREAD

**Issue by adelanre** [jenkinsci/google-chat-notification-plugin#4]
so according the doc, `notifySuccess: 'true'` should work but Jenkins throws the error below; 

```
java.lang.ClassCastException: class io.cnaik.GoogleChatNotification.setNotifySuccess() expects boolean but received class java.lang.String
	at org.jenkinsci.plugins.structs.describable.DescribableModel.coerce(DescribableModel.java:394)
	at org.jenkinsci.plugins.structs.describable.DescribableModel.injectSetters(DescribableModel.java:338)
	at org.jenkinsci.plugins.structs.describable.DescribableModel.instantiate(DescribableModel.java:261)
```

Jenkins version `2.73.3`

Here;s what my post build action looks like; 

```
post {
          always {
            deleteDir()
          }
          success {
            googlechatnotification (
              url: "${CHAT_WEBHOOK_URL}",
              message: """ message to be sent""",
              notifySuccess: 'true'
            )
       }
}
```

**Comment by chiragnaik** [comment]
`post {
          always {
            deleteDir()
          }
          success {
            googlechatnotification (
              url: "${CHAT_WEBHOOK_URL}",
              message: """ message to be sent""",
              notifySuccess: true
            )
       }
}`

Set value of notifySuccess as boolean and not String

**Comment by adelanre** [comment]
perhaps I am doing something wrong; I tried that and it doesn't work for me. 

works = "I get a message in my room"

This works; 

```
post {
          always {
            deleteDir()
          }
          success {
            googlechatnotification (
              url: "${CHAT_WEBHOOK_URL}",
              message: """ message to be sent""",
            )
       }
}
```

This doesn't work; 

```
post {
          always {
            deleteDir()
          }
          success {
            googlechatnotification (
              url: "${CHAT_WEBHOOK_URL}",
              message: """ message to be sent""",
              notifySuccess: true
            )
       }
}
```

**Comment by chiragnaik** [comment]
What exception are you getting when you used notifySuccess as Boolean and not as a String?

**Comment by JeronimoColonSP** [comment]
Same issue.  Passing any boolean parameters doesn't fail but doesn't produce a message.  Leaving off all booleans works.

**Comment by chiragnaik** [comment]
notifySuccess: true -> refers to build.getResult() value equal to success. If you are using pipeline type job then you need to explicitly set currentBuild.result = 'SUCCESS' for successful execution before calling the plugin. Jenkins does not expose build result before the end of the job.

Not specifying any parameters means there will be no check of build.getResult(). Hence it works.
