### ISSUE TITLE
List of available environment variables

### ISSUE THREAD

**Issue by MALPI** [jenkinsci/google-chat-notification-plugin#5]
Is there a way to use environment variables in the message like the number of failed tests or if the build failed at all?

**Comment by chiragnaik** [comment]
You can find list of Token environment variables supported [here](https://ci.jenkins.io/env-vars.html/). 
For e.g. String message = "Hey! Build status for ${JOB_NAME} has ${BUILD_STATUS}" . 
Here token plugin expands this variables and replaces them with actual values.

For custom environment variables created at global level you can form a String message in your Jenkinsfile and pass it to plugin. 
For e.g. custom variable defined at Global environment properties is say NUM_OF_FAILURES
String message = "Hey! Build status for ${JOB_NAME} has ${BUILD_STATUS}. Number of build failure count= " + env.NUM_OF_FAILURES

**Comment by MALPI** [comment]
Sorry for not being explicit, I am actually using the UI to configure the build and not a pipeline file.

**Comment by chiragnaik** [comment]
Token macro variables will work with UI as well. Custom variables will not be replaced. You need to form a string before sending to plugin

**Comment by chris-orchard** [comment]
Can you give an example of how to do this in the UI? I'm not sure where you'd create the sting before passing to the plugin field.

**Comment by chiragnaik** [comment]
You can find list of Token Macro plugin environment variables supported [here](https://ci.jenkins.io/env-vars.html/). You can use any of these variables in your message for example: **${JOB_NAME}** JOB_NAME is one of the Token Macro variable.

**Comment by chris-orchard** [comment]
Thanks but I was asking about using custom environment variables via UI as in this previous comment:

> For custom environment variables created at global level or variables outside above list, you can form a String message in your Jenkinsfile and pass it to plugin.
> For e.g. custom variable defined at Global environment properties is say NUM_OF_FAILURES
> String message = "Hey! Build status for ${JOB_NAME} has ${BUILD_STATUS}. Number of build failure count= " + env.NUM_OF_FAILURES

**Comment by lestinliu** [comment]
Thanks for developing this plugin. Very useful!

Sorry to bring up this issue. My question is related to this line "You need to form a string before sending to plugin"

I'm not using a pipeline job. So how can i construct a string and send it to the chat plugin in traditional freestyle job? I tried to define global variables, export overriding existing variables, none of them worked (maybe I wasn't doing it in the right way).

Could you please help to elaborate a bit as of how to use a custom defined string to the plugin?
Thanks.
