### ISSUE TITLE
Please add support for threading

### ISSUE THREAD

**Issue by gokeefe** [jenkinsci/google-chat-notification-plugin#6]
Google Chat API supports a thread_key so that each notification doesn't appear as a new thread.

https://developers.google.com/hangouts/chat/how-tos/bots-develop#thread_key

Might be as simple as passing the BUILD_TAG variable as the thread_key?

**Comment by chiragnaik** [comment]
Okay, I will think over all use cases and take it up in next release.

**Comment by chiragnaik** [comment]
Format of BUILD_TAG is String of "jenkins-${JOB_NAME}-${BUILD_NUMBER}". All forward slashes ("/") in the JOB_NAME are replaced with dashes ("-"). This will anyway create new thread for each notification as BUILD_NUMBER is going to be different each time.

**Comment by chris-orchard** [comment]
I think this is a great idea. Grouping by JOB_NAME would make the status of different Jenkins jobs in 
chat much clearer.

**Comment by chiragnaik** [comment]
This is released in latest 1.3 release

**Comment by chris-orchard** [comment]
This feature errors when the job name has spaces. See #9 for full details.
