### ISSUE TITLE
Allow message to be customised for different status

### ISSUE THREAD

**Issue by chris-orchard** [jenkinsci/google-chat-notification-plugin#7]
This would allow specific extra text on failures. This could be an extra text field against each Notify x checkbox which is appended to the main 'message' string for that type of message.

**Comment by slux83** [comment]
You can do it this way, via the token plugin
`${PROJECT_NAME} : Build #${BUILD_NUMBER} - ${BUILD_STATUS}: Check output at ${BUILD_URL}`

**Comment by chris-orchard** [comment]
I already do something like that. However I was thinking more along the lines of:

On success:
`${PROJECT_NAME} : Build #${BUILD_NUMBER} - ${BUILD_STATUS}`

On failure:
`${PROJECT_NAME} : Build #${BUILD_NUMBER} - *${BUILD_STATUS}: Check logs at ${BUILD_URL}/logs`

I know I could do this with Jenkins Pipeline style jobs, but we have many older Freestyle jobs that use the Post Build Action step.

Maybe the long term answer is to gradually convert our Freestyle jobs to Pipeline jobs, or at least wrap them with a pipeline that calls the existing job and sends the required customised message based on the result.

Alternatively I may be able to declare a variable elsewhere in the job with the full output required, based on status, then just use that variable as the message in the post build step.

**Comment by MKIERYLUK** [comment]
Hi,
I would like to address the issue that variables like ${PROJECT_NAME} work as simple text in the post-job, but when attempting to pass them in the card message in JSON as shown below, I encounter errors, including a nullpointer exception.

{
  "cards": [
    {
      "header": {
        "title": "Jenkins Notification",
        "imageUrl": "https://www.remoterocketship.com/_next/image?url=%2Fimages%2Fblog%2FJenkins-icon-for-blog.jpg&w=640&q=75",
        "imageStyle": "AVATAR"
      },
      "sections": [
        {
          "widgets": [
            {
              "textParagraph": {
                "text": "${BUILD_STATUS}  : Build #${BUILD_NUMBER} *${PROJECT_NAME}*: Check output at ${BUILD_URL}"
              }
            },
            {
              "buttons": []
            }
          ]
        }
      ]
    }
  ]
}

**Comment by Ryudo302** [comment]
Hi @MKIERYLUK!
This problem was fixed by [this commit](https://github.com/jenkinsci/google-chat-notification-plugin/commit/a1b65cb3c842cf0db73b51f2acd9beaeea310d7e). It'll be included in the next plugin release.
