### ISSUE TITLE
Send message with threading enabled fails when job name contains spaces

### ISSUE THREAD

**Issue by chris-orchard** [jenkinsci/google-chat-notification-plugin#9]
I've just updated my plugin to 1.3 to try out #6, enabled the `Append Notification In Same Thread` checkbox on an existing job and I now get this error in the console log.

`Exception while posting Google Chat message: Illegal character in query at index 173: https://chat.googleapis.com/v1/spaces/...&threadKey=Jenkins Google Chat test`

If I un-check the option it still works as before.

Having tested another job, threading works as expected for Jenkins job names that do not contain spaces so I assume you need to perform some url encoding on the `threadKey`.

**Comment by chiragnaik** [comment]
Issue has been fixed in release 1.4 . Please try and let me know if its working at your end too.

**Comment by chris-orchard** [comment]
I've updated to 1.4 and this is working now, thanks.Feel free to close it.
